DROP TABLE IF EXISTS `diaxeirsi_ipografwn`;
ALTER TABLE `kends`.`fyllo_poreias`
  ADD COLUMN `F_DIATAGIS` VARCHAR(300) NULL AFTER `HMERES_POREIAS`,
  ADD COLUMN `EDYETHA` VARCHAR(250) NULL AFTER `F_DIATAGIS`,
  ADD COLUMN `DATE_ANAXWRISIS_NOS` DATE NULL AFTER `EDYETHA`,
  ADD COLUMN `DATE_DIAGRAFIS_NOS` DATE NULL AFTER `DATE_ANAXWRISIS_NOS`,
  ADD COLUMN `DATE_EGGRAFIS_NOS` DATE NULL AFTER `DATE_DIAGRAFIS_NOS`,
  ADD COLUMN `DATE_PAROUSIASIS_NOS` DATE NULL AFTER `DATE_EGGRAFIS_NOS`,
  ADD COLUMN `LOGOS_NOS` VARCHAR(100) NULL AFTER `DATE_PAROUSIASIS_NOS`,
  ADD COLUMN `F_DIATAGIS_NOS` VARCHAR(300) NULL AFTER `LOGOS_NOS`,
  ADD COLUMN `NOSOKOMEIO` VARCHAR(300) NULL AFTER `F_DIATAGIS_NOS`,
  ADD COLUMN `ONOMA_SXHM` VARCHAR(45) NULL AFTER `NOSOKOMEIO`;

RENAME TABLE `kends`.`fyllo_poreias` TO `kends`.`diaxeirsi_ipografwn`;