ALTER TABLE `kends`.`ken_atomika`
    ADD COLUMN `COLOUR_HAIR` VARCHAR(45) NULL AFTER `TOPO_GENH_KWD_TAUT`,
    ADD COLUMN `COLOUR_EYES` VARCHAR(45) NULL AFTER `COLOUR_HAIR`,
    ADD COLUMN `AR_TAUTOTHTAS` INT(8) NULL AFTER `COLOUR_EYES`;