insert into `kends`.`diplwma_politiko` (DIPL_POLI_KWD, DIPL_POLI_SYN, DIPL_POLI_LEK) values(12,'ΚΑΤ ΑΜ','ΔΙΠΛΩΜΑ AM ΚΑΤΗΓΟΡΙΑΣ ΜΟΤΟΠΟΔΗΛΑΤΟΥ');
insert into `kends`.`diplwma_politiko` (DIPL_POLI_KWD, DIPL_POLI_SYN, DIPL_POLI_LEK) values(13,'ΚΑΤ Α1','ΔΙΠΛΩΜΑ A1 ΚΑΤΗΓΟΡΙΑΣ ΜΟΤΟΣΥΚΛΕΤΑΣ');
insert into `kends`.`diplwma_politiko` (DIPL_POLI_KWD, DIPL_POLI_SYN, DIPL_POLI_LEK) values(14,'ΚΑΤ Α2','ΔΙΠΛΩΜΑ A2 ΚΑΤΗΓΟΡΙΑΣ ΜΟΤΟΣΥΚΛΕΤΑΣ');
insert into `kends`.`diplwma_politiko` (DIPL_POLI_KWD, DIPL_POLI_SYN, DIPL_POLI_LEK) values(51,'ΚΑΤ B1','ΔΙΠΛΩΜΑ B1 ΚΑΤΗΓΟΡΙΑΣ ΤΕΤΡΑΚΥΛΑ');
insert into `kends`.`diplwma_politiko` (DIPL_POLI_KWD, DIPL_POLI_SYN, DIPL_POLI_LEK) values(52,'ΚΑΤ BE','ΔΙΠΛΩΜΑ BE ΚΑΤΗΓΟΡΙΑΣ ΣΥΖΕΥΓΜΕΝΩΝ ΟΧΗΜΑΤΩΝ');
insert into `kends`.`diplwma_politiko` (DIPL_POLI_KWD, DIPL_POLI_SYN, DIPL_POLI_LEK) values(61,'ΚΑΤ C1','ΔΙΠΛΩΜΑ C1 ΚΑΤΗΓΟΡΙΑΣ ΦΟΡΤΗΓΟΥ');
insert into `kends`.`diplwma_politiko` (DIPL_POLI_KWD, DIPL_POLI_SYN, DIPL_POLI_LEK) values(62,'ΚΑΤ C1E','ΔΙΠΛΩΜΑ C1E ΚΑΤΗΓΟΡΙΑΣ ΝΤΑΛΙΚΑΣ ΦΟΡΤΗΓΟΥ');
insert into `kends`.`diplwma_politiko` (DIPL_POLI_KWD, DIPL_POLI_SYN, DIPL_POLI_LEK) values(63,'ΚΑΤ CE','ΔΙΠΛΩΜΑ CE ΚΑΤΗΓΟΡΙΑΣ ΝΤΑΛΙΚΑΣ ΦΟΡΤΗΓΟΥ');
insert into `kends`.`diplwma_politiko` (DIPL_POLI_KWD, DIPL_POLI_SYN, DIPL_POLI_LEK) values(71,'ΚΑΤ D1','ΔΙΠΛΩΜΑ D1 ΚΑΤΗΓΟΡΙΑΣ ΛΕΩΦΟΡΕΙΟΥ');
insert into `kends`.`diplwma_politiko` (DIPL_POLI_KWD, DIPL_POLI_SYN, DIPL_POLI_LEK) values(72,'ΚΑΤ D1E','ΔΙΠΛΩΜΑ D1E ΚΑΤΗΓΟΡΙΑΣ ΝΤΑΛΙΚΑΣ ΛΕΩΦΟΡΕΙΟΥ');
insert into `kends`.`diplwma_politiko` (DIPL_POLI_KWD, DIPL_POLI_SYN, DIPL_POLI_LEK) values(73,'ΚΑΤ DE','ΔΙΠΛΩΜΑ DE ΚΑΤΗΓΟΡΙΑΣ ΝΤΑΛΙΚΑΣ ΛΕΩΦΟΡΕΙΟΥ');
UPDATE `kends`.`diplwma_politiko` SET DIPL_POLI_SYN='ΚΑΤ A',DIPL_POLI_LEK='ΔΙΠΛΩΜΑ A ΚΑΤΗΓΟΡΙΑΣ ΜΟΤΟΣΥΚΛΕΤΑΣ' WHERE DIPL_POLI_KWD=11;
UPDATE `kends`.`diplwma_politiko` SET DIPL_POLI_SYN='ΚΑΤ B',DIPL_POLI_LEK='ΔΙΠΛΩΜΑ Β ΚΑΤΗΓΟΡΙΑΣ ΑΥΤΟΚΙΝΗΤΟΥ' WHERE DIPL_POLI_KWD=21;
UPDATE `kends`.`diplwma_politiko` SET DIPL_POLI_SYN='ΚΑΤ C',DIPL_POLI_LEK='ΔΙΠΛΩΜΑ C ΚΑΤΗΓΟΡΙΑΣ ΦΟΡΤΗΓΟΥ' WHERE DIPL_POLI_KWD=22;
UPDATE `kends`.`diplwma_politiko` SET DIPL_POLI_SYN='ΚΑΤ D',DIPL_POLI_LEK='ΔΙΠΛΩΜΑ D ΚΑΤΗΓΟΡΙΑΣ ΛΕΩΦΟΡΕΙΟΥ' WHERE DIPL_POLI_KWD=23;
UPDATE `kends`.`diplwma_politiko` SET DIPL_POLI_SYN='ΚΑΤ E' WHERE DIPL_POLI_KWD=24;